### ISSUE TITLE
ck-list add @ link item select dropdown shows no highlight

### ISSUE THREAD

**Issue by code-ink-space** [cwilliams5/Midnight-Trilium-Dark-Mode#1]
First of all, thanks for making this theme. The default Dark theme wasn't polished enough for me and your theme was exactly what I wanted.

Just pointing a CSS you might have overlooked. The @ add link list isn't showing a highlight when you go through the list with the keyboard.

``
--active-item-background-color: #033c5;
``
should be:
``
    --active-item-background-color: #0784B5;
``

To make it look like this:
![trilium-add-link-list](https://user-images.githubusercontent.com/47141674/156422602-3acd3d51-c9f4-45b8-9b65-3f0e32916fb2.jpg)

Thanks again for your work on this theme.

**Comment by cwilliams5** [comment]
@code-ink-space An issue report bundled with a fix, thank you very much. I'm glad you like it and appreciate the issue.

Yeah I don't use this feature (i should start!) so missed this. Was afraid their might be missing coverage due to features I don't use. Fixed in latest, added some extra style on top to match the rest of Midnight.

**Comment by cwilliams5** [comment]
Oh, and while developing this update I also found a bug in the dropdown in question and reported it to Trilium:
https://github.com/zadam/trilium/issues/2703
